language: node_js
branches:
  only:
    - master
    - staging
    - /^greenkeeper/.*$/
notifications:
  email: false

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

node_js: "lts/*"
os: linux

cache:
  directories:
    - "node_modules"

install: npm install
before_script:
  - |
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    chmod +x ./cc-test-reporter
    ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - |
    ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
